server:
  port: 9020
spring:
  application:
    name: hc-auth
  profiles:
    active: dev

  cloud:
    #配置中心
    config:
      fail-fast: true
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
      discovery:
        enabled: true
        service-id: hc-config
    nacos:
      discovery:
        server-addr: ${nacos.url}:9010