server:
  port: 8501
  servlet:
    context-path: /register

spring:
  application:
    name: Hc-Register
  security:
    user:
      name: sonake
      password: 123456

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    instance-info-replication-interval-seconds: 30
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/

